package distributed;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.io.*;
import java.util.*;

public class Dude extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		Dude instance = (Dude)new Dude(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new Dude(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return Dude.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new Dude(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return Dude.getReferenceByLocation(new UAL(ual)); }
	public Dude(boolean o, UAN __uan)	{ super(false,__uan); }
	public Dude(boolean o, UAL __ual)	{ super(false,__ual); }
	public Dude(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public Dude(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public Dude(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public Dude()		{  }
	public Dude(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "distributed.Dude", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct (int id, String host, int port, int priority, int tolerance, int actors, Dude left, Russia supervisor) {
		Object[] __arguments = { new Integer(id), host, new Integer(port), new Integer(priority), new Integer(tolerance), new Integer(actors), left, supervisor };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public Dude self;
		public void updateSelf(ActorReference actorReference) {
			((Dude)actorReference).setUAL(getUAL());
			((Dude)actorReference).setUAN(getUAN());
			self = new Dude(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "distributed.Dude$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		int id;
		String host;
		int port;
		int priority;
		int tolerance;
		int actors;
		int replies;
		boolean pastLeader;
		Dude left;
		Russia supervisor;
		void construct(int id, String host, int port, int priority, int tolerance, int actors, Dude left, Russia supervisor){
			this.id = id;
			this.host = host;
			this.port = port;
			this.priority = priority;
			this.tolerance = tolerance;
			this.actors = actors;
			this.pastLeader = false;
			this.left = left;
			this.supervisor = supervisor;
		}
		public void beginGrowth(Dude candidate) {
			replies = 0;
			if (!pastLeader) {{
				{
					// left<-RadialGrowth(candidate, id, priority, 1, true)
					{
						Object _arguments[] = { candidate, id, priority, new Integer(1), true };
						Message message = new Message( self, left, "RadialGrowth", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}		}
		public void RadialReply(Dude candidate, int candidateID, int candidatePriority, boolean leader) {
			replies += 1;
			if (leader) {			{
				// left<-RadialGrowth(candidate, candidateID, candidatePriority, (int)Math.pow(2, replies), leader)
				{
					Object _arguments[] = { candidate, candidateID, candidatePriority, (int)Math.pow(2, replies), leader };
					Message message = new Message( self, left, "RadialGrowth", _arguments, null, null );
					__messages.add( message );
				}
			}
}		}
		public void RadialGrowth(Dude candidate, int candidateID, int candidatePriority, int TTL, boolean leader) {
			if (id==candidateID) {{
				pastLeader = true;
				{
					// supervisor<-election(candidate, candidateID)
					{
						Object _arguments[] = { candidate, candidateID };
						Message message = new Message( self, supervisor, "election", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {if (TTL-1==0) {{
				{
					// candidate<-RadialReply(candidate, candidateID, candidatePriority, leader)
					{
						Object _arguments[] = { candidate, candidateID, candidatePriority, leader };
						Message message = new Message( self, candidate, "RadialReply", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {{
				if (priority>candidatePriority) {{
					if (!pastLeader) {{
						{
							// candidate<-RadialReply(candidate, candidateID, candidatePriority, false)
							{
								Object _arguments[] = { candidate, candidateID, candidatePriority, false };
								Message message = new Message( self, candidate, "RadialReply", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
}					else {{
						{
							// left<-RadialGrowth(candidate, candidateID, candidatePriority, TTL-1, leader)
							{
								Object _arguments[] = { candidate, candidateID, candidatePriority, TTL-1, leader };
								Message message = new Message( self, left, "RadialGrowth", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
}				}
}				else {{
					{
						// left<-RadialGrowth(candidate, candidateID, candidatePriority, TTL-1, leader)
						{
							Object _arguments[] = { candidate, candidateID, candidatePriority, TTL-1, leader };
							Message message = new Message( self, left, "RadialGrowth", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
}}		}
		public void tick(int timestamp, int electionTime, int presidentID, int revolts) {
			if (presidentID==this.id) {{
				if (revolts>((actors-1)/2)) {{
					{
						// supervisor<-depose(this.id, timestamp)
						{
							Object _arguments[] = { this.id, timestamp };
							Message message = new Message( self, supervisor, "depose", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					{
						// left<-tick(timestamp+1, electionTime, presidentID, revolts)
						{
							Object _arguments[] = { timestamp+1, electionTime, presidentID, revolts };
							Message message = new Message( self, left, "tick", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
}			else {if (timestamp-electionTime>tolerance&&timestamp-electionTime-actors<tolerance) {{
				{
					// supervisor<-writeMessage("ID="+this.id+" revolted at t="+timestamp+"\n")
					{
						Object _arguments[] = { "ID="+this.id+" revolted at t="+timestamp+"\n" };
						Message message = new Message( self, supervisor, "writeMessage", _arguments, null, null );
						__messages.add( message );
					}
				}
				{
					// left<-tick(timestamp+1, electionTime, presidentID, revolts+1)
					{
						Object _arguments[] = { timestamp+1, electionTime, presidentID, revolts+1 };
						Message message = new Message( self, left, "tick", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {{
				{
					// left<-tick(timestamp+1, electionTime, presidentID, revolts)
					{
						Object _arguments[] = { timestamp+1, electionTime, presidentID, revolts };
						Message message = new Message( self, left, "tick", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}}		}
		public void setLeft(Dude left) {
			this.left = left;
		}
	}
}