package distributed;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.io.*;
import java.util.*;

public class Dude extends UniversalActor  implements ActorService {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		Dude instance = (Dude)new Dude(uan, ual,null).construct();
		{
			Object[] _arguments = { args };
			instance.send( new Message(instance, instance, "act", _arguments, null, null) );
		}
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new Dude(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return Dude.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new Dude(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return Dude.getReferenceByLocation(new UAL(ual)); }
	public Dude(boolean o, UAN __uan)	{ super(false,__uan); }
	public Dude(boolean o, UAL __ual)	{ super(false,__ual); }

	public Dude(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null,null); }
	public Dude(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual,null); }
	public Dude(UniversalActor.State sourceActor)		{ this(null, null,null);  }
	public Dude()		{  }
	public Dude(UAN __uan, UAL __ual,Object sourceActor) {
		if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			createRemotely(__uan, __ual, "distributed.Dude");
		} else {
			State state = new State(__uan, __ual);
			state.updateSelf(this);
			ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct (int id, String host, int port, int priority, int tolerance, int actors, Dude left, Writer writeroni) {
		Object[] __arguments = { new Integer(id), host, new Integer(port), new Integer(priority), new Integer(tolerance), new Integer(actors), left, writeroni };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State implements salsa.resources.ActorServiceState {
		public Dude self;
		public void updateSelf(ActorReference actorReference) {
			((Dude)actorReference).setUAL(getUAL());
			((Dude)actorReference).setUAN(getUAN());
			self = new Dude(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.muteGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "distributed.Dude$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		int id;
		String host;
		int port;
		int priority;
		int tolerance;
		int actors;
		boolean active;
		boolean pastLeader;
		Writer writeroni;
		Dude left;
		void construct(int id, String host, int port, int priority, int tolerance, int actors, Dude left, Writer writeroni){
			this.id = id;
			this.host = host;
			this.port = port;
			this.priority = priority;
			this.tolerance = tolerance;
			this.actors = actors;
			this.active = false;
			this.pastLeader = false;
			this.left = left;
			this.writeroni = writeroni;
		}
		public void consider(int candidate, int canditatePriority, int timestamp, int elections) {
			if (elections==actors) {{
				{
					// writeroni<-write("End of simulation")
					{
						Object _arguments[] = { "End of simulation" };
						Message message = new Message( self, writeroni, "write", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {if (candidate==this.id) {{
				active = true;
				pastLeader = true;
				{
					// writeroni<-write("ID="+this.id+" became leader at t="+timestamp+"\n")
					{
						Object _arguments[] = { "ID="+this.id+" became leader at t="+timestamp+"\n" };
						Message message = new Message( self, writeroni, "write", _arguments, null, null );
						__messages.add( message );
					}
				}
				{
					// tick(timestamp, timestamp, this.id, 0, elections)
					{
						Object _arguments[] = { timestamp, timestamp, this.id, new Integer(0), elections };
						Message message = new Message( self, self, "tick", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {{
				if (canditatePriority>this.priority) {{
					{
						// this.left<-consider(candidate, canditatePriority, timestamp, elections)
						{
							Object _arguments[] = { candidate, canditatePriority, timestamp, elections };
							Message message = new Message( self, this.left, "consider", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {if (!pastLeader) {{
					{
						// this.left<-consider(this.id, this.priority, timestamp, elections)
						{
							Object _arguments[] = { this.id, this.priority, timestamp, elections };
							Message message = new Message( self, this.left, "consider", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					{
						// this.left<-consider(candidate, canditatePriority, timestamp, elections)
						{
							Object _arguments[] = { candidate, canditatePriority, timestamp, elections };
							Message message = new Message( self, this.left, "consider", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}}			}
}}		}
		public void tick(int timestamp, int electionTime, int presidentID, int revolts, int elections) {
			if (presidentID==this.id) {{
				if (revolts>((actors-1)/2)) {{
					{
						// writeroni<-write("ID="+this.id+" was deposed at t="+timestamp+"\n")
						{
							Object _arguments[] = { "ID="+this.id+" was deposed at t="+timestamp+"\n" };
							Message message = new Message( self, writeroni, "write", _arguments, null, null );
							__messages.add( message );
						}
					}
					active = false;
					{
						// consider(-1, -1, timestamp+1, elections+1)
						{
							Object _arguments[] = { new Integer(-1), new Integer(-1), timestamp+1, elections+1 };
							Message message = new Message( self, self, "consider", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					{
						// left<-tick(timestamp+1, electionTime, presidentID, revolts, elections)
						{
							Object _arguments[] = { timestamp+1, electionTime, presidentID, revolts, elections };
							Message message = new Message( self, left, "tick", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
}			else {if (timestamp-electionTime>tolerance&&timestamp-electionTime-actors<tolerance) {{
				{
					// writeroni<-write("ID="+this.id+" revolted at t="+timestamp+"\n")
					{
						Object _arguments[] = { "ID="+this.id+" revolted at t="+timestamp+"\n" };
						Message message = new Message( self, writeroni, "write", _arguments, null, null );
						__messages.add( message );
					}
				}
				{
					// left<-tick(timestamp+1, electionTime, presidentID, revolts+1, elections)
					{
						Object _arguments[] = { timestamp+1, electionTime, presidentID, revolts+1, elections };
						Message message = new Message( self, left, "tick", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {{
				{
					// left<-tick(timestamp+1, electionTime, presidentID, revolts, elections)
					{
						Object _arguments[] = { timestamp+1, electionTime, presidentID, revolts, elections };
						Message message = new Message( self, left, "tick", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}}		}
		public void setLeft(Dude left) {
			this.left = left;
		}
	}
}